Improving Shopware landing page
storefront-x/storefront-x pull request #127
Opened 2022-10-20 08:37 UTC by JaroslavSku

2022-10-26 11:44 UTC, adamjedlicka requested changes

2022-10-26 11:44 UTC, adamjedlicka commented on modules/cms-shopware/components/SfxShopwareCmsPage.vue
> +        renderedBlock.push(this.renderBlock({ ...block, ...section }))
Wouldnt it be better to change renderBlock to accept object of block and section?

2022-11-01 08:55 UTC, adamjedlicka requested changes

2022-11-01 08:55 UTC, adamjedlicka commented on modules/cms-shopware/components/SfxShopwareCmsPage.vue
> +    renderBlock(group: any) {
Use object spread here `renderBlock({ block, section })`

2022-11-01 08:55 UTC, adamjedlicka commented on modules/cms-shopware/components/SfxShopwareCmsPage.vue
> +      return h(component, { data: properties }, slots)
Why not pass section as secondary prop? `{ data: block, section }`

2022-11-07 10:07 UTC, adamjedlicka requested changes

2022-11-07 10:07 UTC, adamjedlicka commented on modules/cms-shopware/components/SfxShopwareCmsPage.vue
> +    renderBlock(group: any) {
Change to:

```
renderBlock({ block, section })
```

2022-11-07 10:07 UTC, adamjedlicka commented on modules/cms-shopware/components/SfxShopwareCmsPage.vue
> +      return h(component, { data: group, section: group.section }, slots)
Change to:

```
return h(component, { data: block, section }, slots)
```

2022-11-07 10:07 UTC, adamjedlicka commented on modules/cms-shopware/components/SfxShopwareCmsPage.vue
> +        renderedBlock.push(this.renderBlock({ ...block, section }))
Change to:

```
renderedBlock.push(this.renderBlock({ block, section }))
```

2022-11-13 22:26 UTC, closed without merging

2022-11-13 22:27 UTC, JaroslavSku commented
I created a new one with feature-sfx-108