WIP: Vanilla Magento
storefront-x/storefront-x pull request #245
Opened 2023-01-02 13:38 UTC by kubo12312

2023-01-03 08:47 UTC, adamjedlicka requested changes

2023-01-03 08:47 UTC, adamjedlicka commented on modules/create-storefront-x/template/magento/modules/demo-magento/tailwind.config.js
> +    './node_modules/@storefront-x/theme-tailwind-magento-px/**/*.vue',
Do not update create-storefront-x module. That is done only during new release.

2023-01-05 13:33 UTC, magexo-extensions commented
@adamjedlicka  @kubo12312  Can we delete modules related to Venia? I don't thin we need it anymore, when we have Vanilla Magneto.

2023-01-05 13:34 UTC, magexo-extensions commented
@adamjedlicka  @kubo12312  what will be impact on running projects that are currently in production?

2023-01-09 09:10 UTC, adamjedlicka approved these changes

2023-01-09 09:10 UTC, merged