Upgrade Cypress to v12.5
storefront-x/storefront-x pull request #320
Opened 2023-02-02 14:26 UTC by kubo12312

## What does this PR do and why?

Fixing cypress imports from node_modules

## What is added/fixed/removed?

**Fixed**
- imports in cypress vite preprocessor

2023-02-02 20:29 UTC, adamjedlicka requested changes

2023-02-02 20:29 UTC, adamjedlicka commented on modules/demo-px/cypress/e2e/checkout.cy.js
> +    getAppliedCoupons().last().should('have.text', couponName)
Why?

2023-02-06 09:31 UTC, xvyslo05 commented on modules/demo-px/cypress/e2e/checkout.cy.js
> +    getAppliedCoupons().last().should('have.text', couponName)
solved with another commit

2023-02-06 09:57 UTC, adamjedlicka approved these changes

2023-02-06 09:57 UTC, merged